// actionTypes.js

export const GET_ALL_CONTACTS = 'GET_ALL_CONTACTS';
export const CREATE_NEW_CONTACT = 'CREATE_NEW_CONTACT';
export const REMOVE_CONTACT = 'REMOVE_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
// export const MOVE_CONTACT = 'MOVE_CONTACT';
export const TOGGLE_CHECKED = 'TOGGLE_CHECKED';